### ISSUE TITLE
'Error: Invalid flag' is occurred using with '-i' or '-q'.

### ISSUE THREAD

**Issue by kawaken** [kt3k/saku#27]
I run saku then error is occurred.

```
$ saku -q task1 task2
Error: Invalid flag: -q
$ saku -i
Error: Invalid flag: -i
```

saku.md is below.

```
# task1

    echo "run: task1"

# task2

    echo "run: task2"
```

Those options are not implemented yet?

**Comment by kt3k** [comment]
Thanks for pointing it! I completely forgot implementing --quiet and --info flags 😓 

(`saku --info` is the same as `saku` (without arguments). I just forgot handling the flag)

I'll fix it in a few days!

**Comment by kt3k** [comment]
Added -i and -q options in the v1.1.0 release. Thanks again for reporting the issue!
