### ISSUE TITLE
Group tasks with headers

### ISSUE THREAD

**Issue by abraverm** [kt3k/saku#28]
Use headers levels for grouping multiple tasks. For example:
```markdown
# My project
## Setup
### a
### b
```
Will be used as:
```bash
saku Setup
[saku] Run Setup
[saku]   Run a
[saku]   ✨  Finish a
[saku]   Run b
[saku]   ✨  Finish b
[saku] ✨  Finish Setup
```

**Comment by kt3k** [comment]
Thanks for the idea!

I would use this feature like:

````markdown
# build

## js

```
browserify app.js
```
## css

```
sass blah blah
```

````

```console
saku build
```

hmm... seems interesting...!

**Comment by kt3k** [comment]
Probably we need a way to specify whether child nodes should be executed in serial or in parallel.

**Comment by abraverm** [comment]
I think by default it should be serial and with same order as in the document, and that is true for every level. Parallel can be enabled with `-p` option or by adding comment `<!-- saku parallel -->`. Parallel should only work on high level tasks unless specified differently in the comment. For example:
```markdown
# My project
## Setup
### a
<!-- saku parallel -->
#### 1
#### 2
### b
```
The execution results will be:
```bash
$ saku Setup
[saku] Run Setup
[saku]   Run a (Parallel)
[saku]      Run 1 .... ✨  Finish
[saku]      Run 2 .... ✨  Finish
[saku]   ✨  Finish a
[saku]   Run b
[saku]   ✨  Finish b
[saku] ✨  Finish Setup

$ saku -p Setup
[saku] Run Setup (Parallel)
[saku]   Run a (Parallel) .. ✨  Finish
[saku]      Run 1 .... ✨  Finish
[saku]      Run 2 .... ✨  Finish
[saku]   Run b ... ✨  Finish
[saku] ✨  Finish Setup
```
The reason for `.... ✨  Finish` is for visualizing all the tasks that are being executed and their state.

**Comment by kt3k** [comment]
I started prototyping this feature. For grouping and `<!-- saku parallel -->` directive, I'm basically following your suggestion.

I'm aiming a little different goal about logging. My current plan is like the below:

saku.md
````markdown
# foo
## js
<!-- saku parallel -->
### js:build
### js:lint
## css
# bar
````

```console
$ saku foo bar
[saku] Run foo, bar in sequence
[saku] foo > Run js, css in sequence
[saku] foo > js > Run js:build, js:lint in parallel
[saku] foo > js > Finish js:build, js:lint in parallel
[saku] foo > Finish js, css in sequence
[saku] Finish foo, bar in sequence
✨ Done.
```

I prefer not intending lines because saku redirects the internal commands output to saku's output. So actual output looks like the below, and indentation probably doesn't work well among those many log messages.

```console
$ saku foo bar
[saku] Run foo, bar in sequence
blah blah blah
blah blah blah
blah blah blah
[saku] foo > Run js, css in sequence
[saku] foo > js > Run js:build, js:lint in parallel
blah blah blah
blah blah blah
blah blah blah
[saku] foo > js > Finish js:build, js:lint in parallel
blah blah blah
blah blah blah
blah blah blah
[saku] foo > Finish js, css in sequence
[saku] Finish foo, bar in sequence
✨ Done.
```

**Comment by abraverm** [comment]
looks great! thank you :tada:

**Comment by kt3k** [comment]
I hope the feature fits your use case! 😄
