### ISSUE TITLE
Pass arguments to tasks?

### ISSUE THREAD

**Issue by shadowrylander** [kt3k/saku#32]
Hello!
&nbsp;&nbsp;&nbsp;&nbsp; I'm terribly sorry if this has already been asked, or, more likely, you considered this, however, would there be any possible way to pass arguments to `saku`? I absolutely love the fact that you can embed it into the `README`, which is the second reason I chose this, the first being it's speed.
&nbsp;&nbsp;&nbsp;&nbsp; I understand that this may cause issues with cross-compatibility, so no rush in implementing this, if you have plans to at all.
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for your help on the matter!

**Comment by kt3k** [comment]
@ShadowRylander Thanks for the feedback!

> would there be any possible way to pass arguments to saku?

You can pass extra options to the commands in tasks by appending `--` and any arguments at the end. For example:

saku.md
````markdown
# hello

    echo hello
````

The command:
```
saku hello -- xyz
```
`-- xyz` part means to pass `xyz` to the internal command, and then the above executes the command `echo hello xyz`. Is this what you're looking for?

**Comment by shadowrylander** [comment]
Give or take! The syntax is a tad confusing, but I believe I can work with it; can I put multiple arguments as well, or just the one? So something similar to `saku hello -- xyz abc`?

**Comment by kt3k** [comment]
Any number of arguments should work. saku doesn't parse the arguments after `--`, you can do something like this: `saku hello -- xyz --foo bar`. This results executing the command `echo hello xyz --foo bar`

**Comment by shadowrylander** [comment]
Ah, right! Thank you, then! I'll close this issue, now, I think!
