### ISSUE TITLE
Consider renaming the project to `gump`

### ISSUE THREAD

**Issue by kt3k** [kt3k/saku#34]
- I'm planning to renaming the project to `gump`

because `saku` seems a little hard to remember or sounds strange for English speaking audiences.

**Comment by kt3k** [comment]
I chose `gump` at the moment because
- recent task runners tend to have single (or two) syllable names starting with G. e.g. grunt, gulp, gradle, [gobble](https://github.com/gobblejs/gobble).

But I'm still open to other suggestions.

**Comment by shadowrylander** [comment]
If you're still concerned about this, I'd argue being named `saku` makes this project _more_ memorable, not less!

**Comment by kt3k** [comment]
Hey thanks. I'm not planning to change the name anymore
