### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by kt3k** [kt3k/saku#8]

**Comment by kubosho** [comment]
`saku` not supported Windows ? My environment installed `saku` and executed `saku`. `saku` is worked.

My environment is this:

- Windows 10 Pro
  - used PowerShell
  - used Windows subsystems for Linux (OS: Ubuntu)

These environments worked.

**Comment by kt3k** [comment]
@kubosho 
Thanks for checking it! That's great news!

I copied basic things from npm-run-all. Probably that's why the simple use cases just work. I'm still not sure if everything works nicely on windows, for example parallel execution `saku -p` or race parallel execution `saku -rp`. I think we need to set up appveyor CI to fully support windows.

Anyway the above info was really helpful. Thanks!
